### ISSUE TITLE
Import / export from YAML

### ISSUE THREAD

**Issue by stevus** [wpbullet/wp-menu-import-export-cli#6]
Can this package be made to observe the `--format` variable?

**Comment by roelmagdaleno** [comment]
Hi @stevus, the current WP-CLI command version ([v0.1.2](https://github.com/wpbullet/wp-menu-import-export-cli/releases/tag/v0.1.2)) does not support the `--format` option. Right now, it only export and import to JSON file.

If you want, you can add the `--format` option to the code and make a PR.

Thanks.
